### PR TITLE
Fix/session shenanigans

### LINKED ISSUE #21: Reconcile hidden dependencies
Right now we need the user to set up bodyParser and express session implicitly. In both these cases we should either automatically hook them up or find a way to communicate clearly that these need to be there and error if they aren't.

### LINKED ISSUE #33: Error getting accessToken
Hi, I wonder why the accessToken could be retrieved when running locally but Heroku. 
Here's what the error said:

> `GET /auth/shopify?shop=lskdfj.myshopify.com 304 2.288 ms - -
> 2017-12-13T15:57:27.999826+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'accessToken' of undefined
> 2017-12-13T15:57:27.999840+00:00 app[web.1]:     at shopStore.storeShop (/app/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:89:39)
> 2017-12-13T15:57:27.999841+00:00 app[web.1]:     at MemoryStrategy.storeShop (/app/node_modules/@shopify/shopify-express/strategies/MemoryStrategy.js:13:12)
> 2017-12-13T15:57:27.999842+00:00 app[web.1]:     at fetch.then.then.responseBody (/app/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:84:19)
> 2017-12-13T15:57:27.999843+00:00 app[web.1]:     at <anonymous>
> 2017-12-13T15:57:27.999844+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:160:7)
> 2017-12-13T15:57:28.006774+00:00 app[web.1]: (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> 2017-12-13T15:57:28.006860+00:00 app[web.1]: (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

### LINKED ISSUE #45: shopify-express oAuth process breaks when sessions are not configured in express
```
🔴 Error storing shop access token TypeError: Cannot set property 'accessToken' of undefined
    at shopStore.storeShop (/home/benni/myproject/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:89:39)
    at ShopStoreTypeOrmService.<anonymous> (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:49:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:16:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:18153) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'accessToken' of undefined
    at shopStore.storeShop (/home/benni/myproject/node_modules/@shopify/shopify-express/routes/shopifyAuth.js:89:39)
    at ShopStoreTypeOrmService.<anonymous> (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:51:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/benni/myproject/src/shop/services/shop-store-type-orm.service.ts:16:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:18153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't need or want session support in my app.

The problem is that in shopifyAuth.js in the function that handles "/callback" doesn't actually check if a session is available and just blindly tries to save stuff into the session.

```
request.session.accessToken = accessToken;
request.session.shop = shop;
```

### PR DESCRIPTION
**Pull request by TheMallen**
closes #45 
closes #21 
closes #33 

This PR adds some error logic for common gotchas, as well as documentation.

It also fixes `ShopifyAuth` breaking when no session is configured (though I added a warning since most of the package does need one).

### CODE REVIEW

File: routes/shopifyApiProxy.js [hunk 1]
```diff
@@ -15,10 +15,23 @@ const DISALLOWED_URLS = [
 
 module.exports = async function shopifyApiProxy(incomingRequest, response, next) {
   const { query, method, path: pathname, body, session } = incomingRequest;
+
+  if (session == null) {
+    console.error('A session middleware must be installed to use ApiProxy.')
```
Comment (AWaselnuk) [inline routes/shopifyApiProxy.js]: Let's be consistent with names in the logs `shopifyApiProxy`.
